#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
#Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.
#cat <<EOF>> /etc/hosts
#100.25.37.157	www.murithimichael.tech		
#100.25.37.157	lb-01.murithimichael.tech	
#54.146.59.67	web-02.murithimichael.tech	
#54.209.136.208	web-01.murithimichael.tech	
#EOF
configure ()
{
	if [[ -n $1 ]]; then
		if [[ -n $2 ]]
		then
			hostname="$2.$1"
			result=$(dig "$hostname" | awk "/^$hostname/{print}")
			subdomain=$(echo "$result" | awk -F "." '{print $1}')
			record_type=$(echo "$result" | awk '{print $4}')
			destination=$(echo "$result" | awk '{print $5}')
			echo "The subdomain $subdomain is a $record_type record and points to $destination"
		else
			for sub in "www" "lb-01" "web-01" "web-02"
			do
				hostname="$sub.$1"
				result=$(dig "$hostname" | awk "/^$hostname/{print}")
				subdomain=$(echo "$result" | awk -F "." '{print $1}')
				record_type=$(echo "$result" | awk '{print $4}')
				destination=$(echo "$result" | awk '{print $5}')
				echo "The subdomain $subdomain is a $record_type record and points to $destination"
			done
		fi
	fi

}
configure "$1" "$2"
