#!/usr/bin/env bash
#Configure your domain zone (in the get.tech domain)so that the subdomain www points to 
#your load-balancer IP (lb-01).
#Let’s also add other subdomains to make our life easier, 
#and write a Bash script that will display information about subdomains.
configure ()
{
	if [[ -n "$1" ]]; then
		if [[ -n "$2" ]]
		then
			result=$(dig "$2.$1" | awk "/^$2.$1/{print}")
			record_type=$(echo "$result" | awk '{print $4}')
			destination=$(echo "$result" | awk '{print $5}')
			echo "The subdomain $2 is a $record_type record and points to $destination"
		else
			for sub in "www" "lb-01" "web-01" "web-02"
			do
				result=$(dig "$sub.$1" | awk "/^$sub.$1/{print}")
				record_type=$(echo "$result" | awk '{print $4}')
				destination=$(echo "$result" | awk '{print $5}')
				echo "The subdomain $sub is a $record_type record and points to $destination"
			done
		fi
	fi

}
configure "$1" "$2"
