#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to 
#your load-balancer IP (lb-01).
#Let’s also add other subdomains to make our life easier, 
#and write a Bash script that will display information about subdomains.
#sudo cat <<EOF>> /etc/hosts
#100.25.37.157	www.murithimichael.tech		
#100.25.37.157	lb-01.murithimichael.tech	
#54.146.59.67	web-02.murithimichael.tech	
#54.209.136.208	web-01.murithimichael.tech	
#EOF
 dns_look_up () {
    if [ -n "$2" ]
    then
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v vb="$2" '{print "The subdomain " vb " is a " $7 " record and points to " $8}'
    else
	dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain www is a " $7 " record and points to " $8}'
	dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain lb-01 is a " $7 " record and points to " $8}'
	dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-01 is a " $7 " record and points to " $8}'
	dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-02 is a " $7 " record and points to " $8}'
    fi
}

dns_look_up "$1" "$2"
