#!/usr/bin/env bash
#installing nginx web server and configuring redirect
apt-get -y upgrade > /dev/null
apt-get -y install nginx > /dev/null
mkdir -p mkdir /var/www/html
echo "Hello World!" > /var/www/html/index.html > /dev/null
sed -i "s|location / {|location /redirect_me {|" /etc/nginx/sites-available/default
sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g" /etc/nginx/sites-available/default
service nginx start
