#!/usr/bin/env bash
#setting up custom page for error 404
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
echo "Ceci n'est pas une page" > error_404.html
sudo mv index.html /var/www/html
sudo mv error_404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /error_404.html;
   location = /error_404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
