#!/usr/bin/env bash
#installing nginx web server and configuring redirect
apt-get -y upgrade
apt-get -y install nginx 
mkdir -p  /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
cat <<EOF> /etc/nginx/sites-available/default
server {
	listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /error_404.html;
	location = /error_404.html {
		internal;
	}
}
EOF
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
