#!/usr/bin/env bash
# Update package index
apt-get -y upgrade > /dev/null

# Install Nginx
apt-get -y install nginx > /dev/null

# Create directories and files
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = /error_404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply changes
service nginx start
