#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get-update -y
sudo apt-get-install -y 
sudo mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/server {/a\\
	add_header X-Served-By \$host;
	" /etc/nginx/sites-available/default
sudo sed -i "s|location / {|location /redirect_me {|" /etc/nginx/sites-available/default
sudo sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g" /etc/nginx/sites-available/default
sudo service nginx restart
