#!/usr/bin/env bash
#install and configure HAproxy on your lb-01 server.
sudo apt-get -y install --no-install-recommends software-properties-common
sudo sed -i "\$aENABLED=1\n" /etc/default/haproxy
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get -y install haproxy=2.9.\*
cat <<EOF | tee -a /etc/haproxy/haproxy.cfg
frontend  myfrontend
  mode http
  bind *:80 
  default_backend web-servers
backend web-servers
  mode http
  balance roundrobin
  server 531460-web-01 54.209.136.208:80 check
  server 531460-web-02 54.146.59.67:80 check
EOF
sudo service haproxy restart
