#!/usr/bin/env bash
#install and configure HAproxy on your lb-01 server.
#sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get -y install haproxy=2.9.\*
cat <<EOF | tee -a /etc/haproxy/haproxy.cfg
frontend  web-01
  mode http
  bind 54.209.136.208 
  default_backend web-01
frontend web-02
  mode http
  bind 54.146.59.67
  default_backend web-02
backend web-01
  mode http
  balance roundrobin
  server 54.209.136.208  check
backend web-02
  mode http
  balance roundrobin
  server 54.146.59.67 check
EOF
sudo service haproxy restart
