#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd.
#
#Your script should only display:
#
#username
#user id
#Home directory path for the user
#Requirements:
#
#You must use the while loop (for and until are forbidden)
cat /etc/passwd | while read line
do
cut -d':' -f 1,3,6 <<< "$line"
done
