#!/usr/bin/env bash
#script that displays Best School 10 times.
#
#Requirements:
#
#You must use the until loop (for and while are forbidden)
((i=0))
until ((i == 10))
do
	echo "Best School"
	((i++))
done
