#!/usr/bin/env bash
# Fix the container so that Nginx is running as the nginx user.
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 660 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
